import 'package:flutter/material.dart';

List<List<String>> wordHints = [
  ['APPLE', 'A round fruit with a red or green skin'],
  ['BANANA', 'A long, curved fruit with a yellow skin'],
  ['CARROT', 'An orange vegetable that is crunchy and rich in vitamin A'],
  ['FLUTTER', 'A popular mobile app development framework for creating native applications'],
  ['PYTHON', 'A versatile high-level programming language known for its readability'],
  ['CARPOOL', 'The act of sharing a car journey with others to reduce traffic and save costs'],
  ['DUCK', 'A waterbird with a flat bill, webbed feet, and a quacking sound'],
  ['PROGRAMMING', 'The process of writing and executing instructions to create software'],
  ['ELEPHANT', 'A large land mammal with a long trunk and tusks'],
  ['COFFEE', 'A caffeinated beverage made from roasted coffee beans'],
  ['GUITAR', 'A musical instrument with strings that is played by strumming or plucking'],
  ['BEACH', 'A sandy or pebbly shore by the ocean, sea, lake, or river'],
  ['SUNSET', 'The daily event when the sun disappears below the horizon in the evening'],
  ['MOUNTAIN', 'A large natural elevation of the Earth\'s surface that rises steeply'],
  ['RAINBOW', 'A meteorological phenomenon that forms a multicolored circular arc in the sky'],
  ['DOG', 'A domesticated carnivorous mammal'],
  ['CAT', 'A small, typically furry, carnivorous mammal'],
  ['FLOWER', 'The reproductive structure of a plant'],
  ['BOOK', 'A written or printed work that contains pages'],
  ['SCHOOL', 'An institution for education'],
  ['PENCIL', 'A writing instrument with a graphite or lead core'],
  ['NOTEBOOK', 'A book with blank or ruled pages for writing notes'],
  ['RULER', 'A straight measuring tool with marked units of length'],
  ['ERASER', 'A tool used for removing pencil marks'],
  ['BACKPACK', 'A bag used for carrying books and other belongings'],
  ['CALCULATOR', 'A device used for mathematical calculations'],
  ['SCISSORS', 'A cutting tool with two blades and handles'],
  ['GLUE', 'An adhesive substance used for sticking things together'],
  ['CRAYONS', 'Coloring tools made of wax'],
  ['MARKER', 'A pen with a broad tip for writing and drawing'],
  ['SUN', 'The star that is the central body of the solar system'],
  ['CLOUD', 'A visible collection of water droplets or ice crystals in the atmosphere'],
  ['RAIN', 'Water falling from the sky in droplets'],
  ['SNOW', 'Frozen precipitation in the form of white ice crystals'],
  ['WIND', 'The natural movement of air'],
  ['STORM', 'A violent disturbance of the atmosphere'],
  ['SUNNY', 'Having a lot of sunshine'],
  ['COLD', 'Having a low temperature'],
  ['HOT', 'Having a high temperature'],
  ['FOG', 'A thick cloud of tiny water droplets suspended in the air'],
  ['THUNDER', 'The loud sound that follows a flash of lightning'],
];

List<String> letters_hangman = [
  'A',
  'B',
  'C',
  'D',
  'E',
  'F',
  'G',
  'H', 
  'I',
  'J',
  'K',
  'L',
  'M',
  'N',
  'O',
  'P',
  'Q',
  'R',
  'S',
  'T',
  'U',
  'V',
  'W',
  'X',
  'Y', 
  'Z'
];